<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>OrigenesDemo.Tests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\agro-precios\AgroPrecios.csproj" />
        <ProjectReference Include="..\envios-xelaju\EnviosXelaju.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.OpenApi" />
        <PackageReference Include="Microsoft.OpenApi.YamlReader" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <Using Include="FluentAssertions" />
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
