<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Shapi.Aplicacion\Shapi.Aplicacion.csproj" />
        <ProjectReference Include="..\Shapi.Contratos\Shapi.Contratos.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DnsClient" />
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="MailKit" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" />
        <PackageReference Include="Microsoft.OpenApi" />
        <PackageReference Include="Microsoft.OpenApi.YamlReader" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="StackExchange.Redis" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Correo\Plantillas\*.html" />
        <EmbeddedResource Include="Correo\Plantillas\*.txt" />
    </ItemGroup>
</Project>
