// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shapi.Infraestructura.Persistencia;

#nullable disable

namespace Shapi.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ShapiDbContext))]
    [Migration("20260925073244_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("caso_numero_seq")
                .IncrementsBy(10);

            modelBuilder.Entity("Shapi.Dominio.Apis.Api", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Especificacion")
                        .HasColumnType("text")
                        .HasColumnName("especificacion");

                    b.Property<DateTimeOffset?>("EspecificacionCargadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("especificacion_cargada_en");

                    b.Property<string>("EspecificacionDescripcion")
                        .HasColumnType("text")
                        .HasColumnName("especificacion_descripcion");

                    b.Property<string>("EspecificacionFormato")
                        .HasColumnType("text")
                        .HasColumnName("especificacion_formato");

                    b.Property<string>("EspecificacionTitulo")
                        .HasColumnType("text")
                        .HasColumnName("especificacion_titulo");

                    b.Property<string>("EspecificacionVersion")
                        .HasColumnType("text")
                        .HasColumnName("especificacion_version");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.Property<string>("PortalBienvenida")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("portal_bienvenida");

                    b.Property<string>("PortalColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasDefaultValue("#3B6FF0")
                        .HasColumnName("portal_color")
                        .IsFixedLength();

                    b.Property<byte[]>("PortalLogo")
                        .HasColumnType("bytea")
                        .HasColumnName("portal_logo");

                    b.Property<string>("PortalLogoTipo")
                        .HasColumnType("text")
                        .HasColumnName("portal_logo_tipo");

                    b.Property<string>("PortalNombre")
                        .HasColumnType("text")
                        .HasColumnName("portal_nombre");

                    b.Property<DateTimeOffset?>("PublicadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicada_en");

                    b.Property<string>("SecretoOrigenCifrado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secreto_origen_cifrado");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subdominio");

                    b.Property<string>("UrlOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_origen");

                    b.HasKey("Id")
                        .HasName("pk_api");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_api_organizacion_id");

                    b.HasIndex("Subdominio")
                        .IsUnique()
                        .HasDatabaseName("ix_api_subdominio");

                    b.ToTable("api", null, t =>
                        {
                            t.HasCheckConstraint("CK_api_especificacion_formato", "especificacion_formato IS NULL OR especificacion_formato IN ('json','yaml')");

                            t.HasCheckConstraint("CK_api_estado", "estado IN ('borrador','publicada','despublicada')");

                            t.HasCheckConstraint("CK_api_portal_color", "portal_color ~ '^#[0-9A-Fa-f]{6}$'");

                            t.HasCheckConstraint("CK_api_portal_logo_tipo", "portal_logo_tipo IS NULL OR portal_logo_tipo IN ('image/png','image/svg+xml')");

                            t.HasCheckConstraint("CK_api_subdominio", "subdominio ~ '^[a-z0-9][a-z0-9-]{1,28}[a-z0-9]$'");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Apis.DominioPropio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DestinoCname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino_cname");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dominio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset?>("UltimoIntentoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_intento_en");

                    b.Property<DateTimeOffset?>("VerificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificado_en");

                    b.HasKey("Id")
                        .HasName("pk_dominio_propio");

                    b.HasIndex("ApiId")
                        .IsUnique()
                        .HasDatabaseName("ix_dominio_propio_api_id");

                    b.HasIndex("Dominio")
                        .IsUnique()
                        .HasDatabaseName("ix_dominio_propio_dominio");

                    b.ToTable("dominio_propio", null, t =>
                        {
                            t.HasCheckConstraint("CK_dominio_propio_estado", "estado IN ('pendiente','verificado','fallido')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Apis.RegistroDnsSimulado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_registro_dns_simulado");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_registro_dns_simulado_nombre");

                    b.ToTable("registro_dns_simulado", null, t =>
                        {
                            t.HasCheckConstraint("CK_registro_dns_tipo", "tipo IN ('CNAME')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Apis.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<int>("CacheSegundos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cache_segundos");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Definicion")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definicion");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Expuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("expuesta");

                    b.Property<int?>("LimiteMinuto")
                        .HasColumnType("integer")
                        .HasColumnName("limite_minuto");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metodo");

                    b.Property<string>("Patron")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patron");

                    b.Property<int>("PesoLlamadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("peso_llamadas");

                    b.Property<string>("Resumen")
                        .HasColumnType("text")
                        .HasColumnName("resumen");

                    b.HasKey("Id")
                        .HasName("pk_ruta");

                    b.HasIndex("ApiId", "Metodo", "Patron")
                        .IsUnique()
                        .HasDatabaseName("ix_ruta_api_id_metodo_patron");

                    b.ToTable("ruta", null, t =>
                        {
                            t.HasCheckConstraint("CK_ruta_cache_segundos", "cache_segundos BETWEEN 0 AND 86400");

                            t.HasCheckConstraint("CK_ruta_limite_minuto", "limite_minuto IS NULL OR limite_minuto > 0");

                            t.HasCheckConstraint("CK_ruta_metodo", "metodo IN ('GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS')");

                            t.HasCheckConstraint("CK_ruta_peso_llamadas", "peso_llamadas BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Bitacora.EntradaBitacora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_nombre");

                    b.Property<string>("ActorTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_tipo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Detalle")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<DateTimeOffset>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<Guid?>("ObjetivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("objetivo_id");

                    b.Property<string>("ObjetivoTipo")
                        .HasColumnType("text")
                        .HasColumnName("objetivo_tipo");

                    b.Property<Guid?>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.HasKey("Id")
                        .HasName("pk_bitacora");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_bitacora_organizacion_id");

                    b.ToTable("bitacora", null, t =>
                        {
                            t.HasCheckConstraint("CK_bitacora_actor_tipo", "actor_tipo IN ('usuario','consumidor','sistema')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Claves.Clave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash_sha256")
                        .IsFixedLength();

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefijo");

                    b.Property<DateTimeOffset?>("RevocadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocada_en");

                    b.Property<string>("RevocadaPor")
                        .HasColumnType("text")
                        .HasColumnName("revocada_por");

                    b.Property<Guid>("SuscripcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suscripcion_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Ultimos4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("ultimos4")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_clave");

                    b.HasIndex("HashSha256")
                        .IsUnique()
                        .HasDatabaseName("ix_clave_hash_sha256");

                    b.HasIndex("SuscripcionId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_clave_suscripcion_id_tipo")
                        .HasFilter("estado = 'activa'");

                    b.ToTable("clave", null, t =>
                        {
                            t.HasCheckConstraint("CK_clave_estado", "estado IN ('activa','rotada','revocada')");

                            t.HasCheckConstraint("CK_clave_revocada_por", "revocada_por IS NULL OR revocada_por IN ('consumidor','proveedor')");

                            t.HasCheckConstraint("CK_clave_tipo", "tipo IN ('produccion','pruebas')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Consumo.ConsumoDiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<long>("BytesEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("bytes_entrada");

                    b.Property<long>("BytesSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("bytes_salida");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entorno");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.PrimitiveCollection<int[]>("HistLatenciaCompuerta")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("hist_latencia_compuerta");

                    b.PrimitiveCollection<int[]>("HistLatenciaTotal")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("hist_latencia_total");

                    b.Property<long>("LatenciaCompuertaSumaMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latencia_compuerta_suma_ms");

                    b.Property<long>("LatenciaTotalSumaMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latencia_total_suma_ms");

                    b.Property<long>("Llamadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("llamadas");

                    b.Property<long>("Origen2xx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("origen2xx");

                    b.Property<long>("Origen3xx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("origen3xx");

                    b.Property<long>("Origen4xx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("origen4xx");

                    b.Property<long>("Origen5xx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("origen5xx");

                    b.Property<long>("OrigenFallo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("origen_fallo");

                    b.Property<long>("Peticiones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("peticiones");

                    b.Property<long>("Rechazos401")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("rechazos401");

                    b.Property<long>("Rechazos403")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("rechazos403");

                    b.Property<long>("Rechazos404")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("rechazos404");

                    b.Property<long>("Rechazos429")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("rechazos429");

                    b.Property<Guid?>("RutaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruta_id");

                    b.Property<Guid?>("SuscripcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suscripcion_id");

                    b.HasKey("Id")
                        .HasName("pk_consumo_diario");

                    b.HasIndex("RutaId")
                        .HasDatabaseName("ix_consumo_diario_ruta_id");

                    b.HasIndex("ApiId", "Fecha")
                        .HasDatabaseName("ix_consumo_diario_api_id_fecha");

                    b.HasIndex("SuscripcionId", "Fecha")
                        .HasDatabaseName("ix_consumo_diario_suscripcion_id_fecha");

                    b.HasIndex("Fecha", "ApiId", "RutaId", "SuscripcionId", "Entorno")
                        .IsUnique()
                        .HasDatabaseName("ix_consumo_diario_fecha_api_id_ruta_id_suscripcion_id_entorno");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Fecha", "ApiId", "RutaId", "SuscripcionId", "Entorno"), false);

                    b.ToTable("consumo_diario", null, t =>
                        {
                            t.HasCheckConstraint("CK_consumo_entorno", "entorno IN ('produccion','pruebas')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Consumo.LoteConsolidado", b =>
                {
                    b.Property<Guid>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.HasKey("LoteId")
                        .HasName("pk_lote_consolidado");

                    b.ToTable("lote_consolidado", (string)null);
                });

            modelBuilder.Entity("Shapi.Dominio.Correo.CorreoSaliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asunto");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("datos");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinatario");

                    b.Property<DateTimeOffset?>("EnviadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos");

                    b.Property<string>("Plantilla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plantilla");

                    b.Property<DateTimeOffset?>("ProximoIntentoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proximo_intento_en");

                    b.Property<string>("UltimoError")
                        .HasColumnType("text")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id")
                        .HasName("pk_correo_saliente");

                    b.ToTable("correo_saliente", null, t =>
                        {
                            t.HasCheckConstraint("CK_correo_saliente_estado", "estado IN ('pendiente','enviado','fallido')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Identidad.Consumidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset?>("CorreoVerificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correo_verificado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_empresa");

                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.HasKey("Id")
                        .HasName("pk_consumidor");

                    b.HasIndex("OrganizacionId", "Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_consumidor_organizacion_id_correo");

                    b.ToTable("consumidor", null, t =>
                        {
                            t.HasCheckConstraint("CK_consumidor_estado", "estado IN ('activo','desactivado')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Identidad.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgenteUsuario")
                        .HasColumnType("text")
                        .HasColumnName("agente_usuario");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ambito");

                    b.Property<Guid?>("ConsumidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumidor_id");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashIdentificador")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash_identificador")
                        .IsFixedLength();

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset?>("RevocadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocada_en");

                    b.Property<DateTimeOffset>("UltimoUsoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso_en");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sesion");

                    b.HasIndex("ConsumidorId")
                        .HasDatabaseName("ix_sesion_consumidor_id");

                    b.HasIndex("HashIdentificador")
                        .IsUnique()
                        .HasDatabaseName("ix_sesion_hash_identificador");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sesion_usuario_id");

                    b.ToTable("sesion", null, t =>
                        {
                            t.HasCheckConstraint("CK_sesion_actor", "num_nonnulls(usuario_id, consumidor_id) = 1");

                            t.HasCheckConstraint("CK_sesion_ambito", "ambito IN ('personal','consumidor')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Identidad.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConsumidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumidor_id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash_token")
                        .IsFixedLength();

                    b.Property<Guid?>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.Property<string>("Rol")
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_token");

                    b.HasIndex("ConsumidorId")
                        .HasDatabaseName("ix_token_consumidor_id");

                    b.HasIndex("HashToken")
                        .IsUnique()
                        .HasDatabaseName("ix_token_hash_token");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_token_organizacion_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_token_usuario_id");

                    b.ToTable("token", null, t =>
                        {
                            t.HasCheckConstraint("CK_token_tipo", "tipo IN ('verificacion_correo','recuperacion','invitacion_miembro','invitacion_consumidor','definir_contrasena')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Identidad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset?>("CorreoVerificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correo_verificado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("HashContrasena")
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_correo");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("CK_usuario_estado", "estado IN ('activo','desactivado')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Organizaciones.Membresia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_membresia");

                    b.HasIndex("OrganizacionId")
                        .IsUnique()
                        .HasDatabaseName("ix_membresia_organizacion_id")
                        .HasFilter("rol = 'propietario'");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_membresia_usuario_id");

                    b.ToTable("membresia", null, t =>
                        {
                            t.HasCheckConstraint("CK_membresia_rol", "rol IN ('administrador','soporte','propietario','editor','lector')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Organizaciones.Organizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EstadoAdmin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_admin");

                    b.Property<string>("MotivoSuspension")
                        .HasColumnType("text")
                        .HasColumnName("motivo_suspension");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_organizacion");

                    b.HasIndex("Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_organizacion_tipo")
                        .HasFilter("tipo = 'plataforma'");

                    b.ToTable("organizacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_organizacion_estado_admin", "estado_admin IN ('activa','suspendida')");

                            t.HasCheckConstraint("CK_organizacion_tipo", "tipo IN ('plataforma','proveedor')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Pagos.MedioPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AnioVencimiento")
                        .HasColumnType("smallint")
                        .HasColumnName("anio_vencimiento");

                    b.Property<Guid?>("ConsumidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumidor_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<short>("MesVencimiento")
                        .HasColumnType("smallint")
                        .HasColumnName("mes_vencimiento");

                    b.Property<Guid?>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titular");

                    b.Property<string>("TokenPasarela")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_pasarela");

                    b.Property<string>("Ultimos4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("ultimos4")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_medio_pago");

                    b.HasIndex("ConsumidorId")
                        .HasDatabaseName("ix_medio_pago_consumidor_id");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_medio_pago_organizacion_id");

                    b.ToTable("medio_pago", null, t =>
                        {
                            t.HasCheckConstraint("CK_medio_pago_marca", "marca IN ('Visa','Mastercard','American Express')");

                            t.HasCheckConstraint("CK_medio_pago_org_cons", "num_nonnulls(organizacion_id, consumidor_id) = 1");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Pagos.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<Guid?>("MedioPagoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medio_pago_id");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text")
                        .HasColumnName("motivo_rechazo");

                    b.Property<DateTimeOffset?>("PeriodoFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_fin");

                    b.Property<DateTimeOffset?>("PeriodoInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_inicio");

                    b.Property<string>("ReferenciaPasarela")
                        .HasColumnType("text")
                        .HasColumnName("referencia_pasarela");

                    b.Property<DateTimeOffset?>("RevertidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revertido_en");

                    b.Property<Guid?>("RevertidoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("revertido_por");

                    b.Property<Guid?>("SuscripcionApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("suscripcion_api_id");

                    b.Property<Guid?>("SuscripcionPlataformaId")
                        .HasColumnType("uuid")
                        .HasColumnName("suscripcion_plataforma_id");

                    b.HasKey("Id")
                        .HasName("pk_pago");

                    b.HasIndex("CreadoEn")
                        .IsDescending()
                        .HasDatabaseName("ix_pago_creado_en");

                    b.HasIndex("MedioPagoId")
                        .HasDatabaseName("ix_pago_medio_pago_id");

                    b.HasIndex("RevertidoPor")
                        .HasDatabaseName("ix_pago_revertido_por");

                    b.HasIndex("SuscripcionApiId", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_pago_suscripcion_api_id_creado_en");

                    b.HasIndex("SuscripcionPlataformaId", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_pago_suscripcion_plataforma_id_creado_en");

                    b.ToTable("pago", null, t =>
                        {
                            t.HasCheckConstraint("CK_pago_concepto", "concepto IN ('contratacion','renovacion','cambio_plan','reactivacion')");

                            t.HasCheckConstraint("CK_pago_estado", "estado IN ('autorizado','rechazado','revertido')");

                            t.HasCheckConstraint("CK_pago_monto", "monto > 0");

                            t.HasCheckConstraint("CK_pago_suscripcion", "num_nonnulls(suscripcion_plataforma_id, suscripcion_api_id) = 1");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Planes.PlanApi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CuotaLlamadas")
                        .HasColumnType("bigint")
                        .HasColumnName("cuota_llamadas");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsGratuito")
                        .HasColumnType("boolean")
                        .HasColumnName("es_gratuito");

                    b.Property<int>("LimiteMinuto")
                        .HasColumnType("integer")
                        .HasColumnName("limite_minuto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio");

                    b.Property<int>("VigenciaDias")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia_dias");

                    b.HasKey("Id")
                        .HasName("pk_plan_api");

                    b.HasIndex("ApiId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_api_api_id_nombre");

                    b.ToTable("plan_api", null, t =>
                        {
                            t.HasCheckConstraint("CK_plan_api_cuota", "cuota_llamadas > 0");

                            t.HasCheckConstraint("CK_plan_api_gratuito", "NOT es_gratuito OR precio = 0");

                            t.HasCheckConstraint("CK_plan_api_limite", "limite_minuto > 0");

                            t.HasCheckConstraint("CK_plan_api_precio", "precio >= 0");

                            t.HasCheckConstraint("CK_plan_api_vigencia", "vigencia_dias BETWEEN 1 AND 366");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Planes.PlanPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CuotaPeticiones")
                        .HasColumnType("bigint")
                        .HasColumnName("cuota_peticiones");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("DominioPropio")
                        .HasColumnType("boolean")
                        .HasColumnName("dominio_propio");

                    b.Property<bool>("EsPrueba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_prueba");

                    b.Property<int?>("MaxApis")
                        .HasColumnType("integer")
                        .HasColumnName("max_apis");

                    b.Property<int?>("MaxMiembros")
                        .HasColumnType("integer")
                        .HasColumnName("max_miembros");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio");

                    b.Property<int>("VigenciaDias")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia_dias");

                    b.HasKey("Id")
                        .HasName("pk_plan_plataforma");

                    b.HasIndex("EsPrueba")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_plataforma_es_prueba")
                        .HasFilter("es_prueba = true");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_plataforma_nombre");

                    b.ToTable("plan_plataforma", null, t =>
                        {
                            t.HasCheckConstraint("CK_plan_plataforma_cuota", "cuota_peticiones > 0");

                            t.HasCheckConstraint("CK_plan_plataforma_precio", "precio >= 0");

                            t.HasCheckConstraint("CK_plan_plataforma_vigencia", "vigencia_dias BETWEEN 1 AND 366");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Soporte.Caso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<Guid?>("AsignadoA")
                        .HasColumnType("uuid")
                        .HasColumnName("asignado_a");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("asunto");

                    b.Property<DateTimeOffset?>("CerradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Numero"), "caso_numero_seq");

                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.HasKey("Id")
                        .HasName("pk_caso");

                    b.HasIndex("ApiId")
                        .HasDatabaseName("ix_caso_api_id");

                    b.HasIndex("AsignadoA")
                        .HasDatabaseName("ix_caso_asignado_a");

                    b.HasIndex("CreadoPor")
                        .HasDatabaseName("ix_caso_creado_por");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_caso_numero");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_caso_organizacion_id");

                    b.ToTable("caso", null, t =>
                        {
                            t.HasCheckConstraint("CK_caso_estado", "estado IN ('abierto','cerrado')");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Soporte.CasoMensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("caso_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.HasKey("Id")
                        .HasName("pk_caso_mensaje");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_caso_mensaje_autor_id");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("ix_caso_mensaje_caso_id");

                    b.ToTable("caso_mensaje", (string)null);
                });

            modelBuilder.Entity("Shapi.Dominio.Suscripciones.SuscripcionApi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<Guid>("ConsumidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumidor_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTimeOffset?>("GraciaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gracia_hasta");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<Guid?>("MedioPagoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medio_pago_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid?>("PlanSiguienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_siguiente_id");

                    b.HasKey("Id")
                        .HasName("pk_suscripcion_api");

                    b.HasIndex("ApiId")
                        .HasDatabaseName("ix_suscripcion_api_api_id");

                    b.HasIndex("MedioPagoId")
                        .HasDatabaseName("ix_suscripcion_api_medio_pago_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_suscripcion_api_plan_id");

                    b.HasIndex("ConsumidorId", "ApiId")
                        .IsUnique()
                        .HasDatabaseName("ix_suscripcion_api_consumidor_id_api_id")
                        .HasFilter("estado <> 'finalizada'");

                    b.HasIndex("Estado", "Fin")
                        .HasDatabaseName("ix_suscripcion_api_estado_fin");

                    b.HasIndex("Estado", "GraciaHasta")
                        .HasDatabaseName("ix_suscripcion_api_estado_gracia_hasta");

                    b.ToTable("suscripcion_api", null, t =>
                        {
                            t.HasCheckConstraint("CK_suscripcion_api_estado", "estado IN ('activa','en_gracia','suspendida','finalizada')");

                            t.HasCheckConstraint("CK_suscripcion_api_fechas", "fin > inicio");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Suscripciones.SuscripcionPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTimeOffset?>("GraciaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gracia_hasta");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<Guid?>("MedioPagoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medio_pago_id");

                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid?>("PlanSiguienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_siguiente_id");

                    b.HasKey("Id")
                        .HasName("pk_suscripcion_plataforma");

                    b.HasIndex("MedioPagoId")
                        .HasDatabaseName("ix_suscripcion_plataforma_medio_pago_id");

                    b.HasIndex("OrganizacionId")
                        .IsUnique()
                        .HasDatabaseName("ix_suscripcion_plataforma_organizacion_id")
                        .HasFilter("estado <> 'finalizada'");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_suscripcion_plataforma_plan_id");

                    b.HasIndex("Estado", "Fin")
                        .HasDatabaseName("ix_suscripcion_plataforma_estado_fin");

                    b.HasIndex("Estado", "GraciaHasta")
                        .HasDatabaseName("ix_suscripcion_plataforma_estado_gracia_hasta");

                    b.ToTable("suscripcion_plataforma", null, t =>
                        {
                            t.HasCheckConstraint("CK_suscripcion_plat_estado", "estado IN ('activa','en_gracia','suspendida','finalizada')");

                            t.HasCheckConstraint("CK_suscripcion_plat_fechas", "fin > inicio");
                        });
                });

            modelBuilder.Entity("Shapi.Dominio.Apis.Api", b =>
                {
                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_organizacion_organizacion_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Apis.DominioPropio", b =>
                {
                    b.HasOne("Shapi.Dominio.Apis.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dominio_propio_api_api_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Apis.Ruta", b =>
                {
                    b.HasOne("Shapi.Dominio.Apis.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ruta_api_api_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Bitacora.EntradaBitacora", b =>
                {
                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bitacora_organizacion_organizacion_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Claves.Clave", b =>
                {
                    b.HasOne("Shapi.Dominio.Suscripciones.SuscripcionApi", null)
                        .WithMany()
                        .HasForeignKey("SuscripcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clave_suscripcion_api_suscripcion_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Consumo.ConsumoDiario", b =>
                {
                    b.HasOne("Shapi.Dominio.Apis.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumo_diario_api_api_id");

                    b.HasOne("Shapi.Dominio.Apis.Ruta", null)
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_consumo_diario_ruta_ruta_id");

                    b.HasOne("Shapi.Dominio.Suscripciones.SuscripcionApi", null)
                        .WithMany()
                        .HasForeignKey("SuscripcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_consumo_diario_suscripcion_api_suscripcion_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Identidad.Consumidor", b =>
                {
                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumidor_organizacion_organizacion_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Identidad.Sesion", b =>
                {
                    b.HasOne("Shapi.Dominio.Identidad.Consumidor", null)
                        .WithMany()
                        .HasForeignKey("ConsumidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sesion_consumidor_consumidor_id");

                    b.HasOne("Shapi.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sesion_usuario_usuario_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Identidad.Token", b =>
                {
                    b.HasOne("Shapi.Dominio.Identidad.Consumidor", null)
                        .WithMany()
                        .HasForeignKey("ConsumidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_token_consumidor_consumidor_id");

                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_token_organizacion_organizacion_id");

                    b.HasOne("Shapi.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_token_usuario_usuario_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Organizaciones.Membresia", b =>
                {
                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membresia_organizacion_organizacion_id");

                    b.HasOne("Shapi.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membresia_usuario_usuario_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Pagos.MedioPago", b =>
                {
                    b.HasOne("Shapi.Dominio.Identidad.Consumidor", null)
                        .WithMany()
                        .HasForeignKey("ConsumidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medio_pago_consumidor_consumidor_id");

                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medio_pago_organizacion_organizacion_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Pagos.Pago", b =>
                {
                    b.HasOne("Shapi.Dominio.Pagos.MedioPago", null)
                        .WithMany()
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pago_medio_pago_medio_pago_id");

                    b.HasOne("Shapi.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("RevertidoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pago_usuario_revertido_por");

                    b.HasOne("Shapi.Dominio.Suscripciones.SuscripcionApi", null)
                        .WithMany()
                        .HasForeignKey("SuscripcionApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pago_suscripcion_api_suscripcion_api_id");

                    b.HasOne("Shapi.Dominio.Suscripciones.SuscripcionPlataforma", null)
                        .WithMany()
                        .HasForeignKey("SuscripcionPlataformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pago_suscripcion_plataforma_suscripcion_plataforma_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Planes.PlanApi", b =>
                {
                    b.HasOne("Shapi.Dominio.Apis.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_api_api_api_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Soporte.Caso", b =>
                {
                    b.HasOne("Shapi.Dominio.Apis.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_caso_api_api_id");

                    b.HasOne("Shapi.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AsignadoA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_caso_usuario_asignado_a");

                    b.HasOne("Shapi.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caso_usuario_creado_por");

                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caso_organizacion_organizacion_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Soporte.CasoMensaje", b =>
                {
                    b.HasOne("Shapi.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caso_mensaje_usuario_autor_id");

                    b.HasOne("Shapi.Dominio.Soporte.Caso", null)
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caso_mensaje_caso_caso_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Suscripciones.SuscripcionApi", b =>
                {
                    b.HasOne("Shapi.Dominio.Apis.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_api_api_api_id");

                    b.HasOne("Shapi.Dominio.Identidad.Consumidor", null)
                        .WithMany()
                        .HasForeignKey("ConsumidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_api_consumidor_consumidor_id");

                    b.HasOne("Shapi.Dominio.Pagos.MedioPago", null)
                        .WithMany()
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_suscripcion_api_medio_pago_medio_pago_id");

                    b.HasOne("Shapi.Dominio.Planes.PlanApi", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_api_plan_api_plan_id");
                });

            modelBuilder.Entity("Shapi.Dominio.Suscripciones.SuscripcionPlataforma", b =>
                {
                    b.HasOne("Shapi.Dominio.Pagos.MedioPago", null)
                        .WithMany()
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_suscripcion_plataforma_medio_pago_medio_pago_id");

                    b.HasOne("Shapi.Dominio.Organizaciones.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_plataforma_organizacion_organizacion_id");

                    b.HasOne("Shapi.Dominio.Planes.PlanPlataforma", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_plataforma_plan_plataforma_plan_id");
                });
#pragma warning restore 612, 618
        }
    }
}
