<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <ProjectReference Include="..\Shapi.Aplicacion\Shapi.Aplicacion.csproj" />
        <ProjectReference Include="..\Shapi.Contratos\Shapi.Contratos.csproj" />
        <ProjectReference Include="..\Shapi.Infraestructura\Shapi.Infraestructura.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
